# Generated by Django 5.0.6 on 2024-05-22 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='upload',
        ),
    ]
